Michelle branch
gemstackio/jobs_api pull request #7
Opened 2023-07-11 00:09 UTC by luvkogepan

2023-07-11 04:12 UTC, komeally approved these changes

2023-07-11 15:49 UTC, shokoladber approved these changes
Dope.

2023-07-21 02:26 UTC, blakexcosta requested changes
Code looks good overall. Just remove whitespace in the two functions mentioned

2023-07-21 02:26 UTC, blakexcosta commented on controllers/homepage.go
Remove whitespace in `goDotEnvVariable` and `GoogleSearchAPI` methods

2023-07-22 00:56 UTC, closed without merging